sudo: required
services:
  - docker

before_install:
  - docker build -t ksilvione/react-test -f ./client/Dockerfile.dev ./client

sript:
   - docker run -e CI=true ksilvione/react-test npm run test -- --coverage

after_success:
  - docker build -t ksilvione/multi-client ./client
  - docker build -t ksilvione/multi-nginx ./nginx
  - docker build -t ksilvione/multi-server ./server
  - docker build -t ksilvione/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ksilvione/multi-client
  - docker push ksilvione/multi-nginx
  - docker push ksilvione/multi-server
  - docker push ksilvione/multi-worker
  